### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by xlzhen-940218** [Yuandiaodiaodiao/PyScrcpy#1]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\xlzhen\Downloads\PyScrcpy-master\server\server2.py", line 122, in <module>
    dll = ctypes.CDLL('lib/server8.dll')
  File "D:\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by Yuandiaodiaodiao** [comment]
可能是系统版本和dll版本对不上 重新编译一下server/ffmpegLib的项目就好了

**Comment by zzh666666** [comment]
OSError: [WinError 126] 找不到指定的模块。
我的操作步骤：
1.下载源码后直接main.py,提示OSError: [WinError 126] 找不到指定的模块。（但是打开其他dll文件正常）
2，下载vs2019,并将server ffmpeglib 重新生成，而且server/server2.py里面所需要的server8.dll确实重新生成成功
3.运行依旧找不到指定模块

**Comment by zzh666666** [comment]
> OSError: [WinError 126] 找不到指定的模块。
> 我的操作步骤：
> 1.下载源码后直接main.py,提示OSError: [WinError 126] 找不到指定的模块。（但是打开其他dll文件正常）
> 2，下载vs2019,并将server ffmpeglib 重新生成，而且server/server2.py里面所需要的server8.dll确实重新生成成功
> 3.运行依旧找不到指定模块

win10 x64 ,python  3.7 ,vs2019

**Comment by Yuandiaodiaodiao** [comment]
https://github.com/Yuandiaodiaodiao/PyScrcpy#dll%E4%BE%9D%E8%B5%96%E9%97%AE%E9%A2%98
